K62-RML-statistic_and_recommendation/mainApp/urls.py
from django.urls import path
from . import views
from . import adminviews
from .viewapi import showviewlearningoutcomeview

urlpatterns = [
    # path('login/', adminviews.login_page, name='login'),
    path('login/', adminviews.user_login, name='login'),
    path('logout/', adminviews.user_logout, name='logout'),

    # path('changepassword/', views.changepassword_page, name='changepassword'),

    # path('viewlearningoutcome/', showviewlearningoutcomeview.viewlearningoutcome, name='viewlearningoutcome'),

    # path('suggestioncourse/', views.suggestioncourse_page, name='suggestioncourse'),
    # path('scoreforecast/', views.scoreforecast_page, name='scoreforecast'),
    # path('statistical/', views.statistical_page, name='statistical'),
    # path('statisticals/', views.statistical_page, name = 'statistical1'),
    # path('process_data/<str:save>/<str:course>', views.get_distribute),
    # path('transcripts/<str:unit>/<str:gen>/<str:group>/<str:sem>', views.transcript),
    # path('transcript_file_process', views.transcript_file_process),
]

K62-RML-statistic_and_recommendation/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf.urls import url
from django.views.static import serve

from django.conf import settings
from django.conf.urls.static import static

from project import settings
from statistic import urls as st_urls
from recommendation import urls as rec_urls
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', TemplateView.as_view(template_name="home.html"), name = 'trangchu'),
    path('', views.home_page, name = "trangchu"),
    path('', include('mainApp.urls')),
    path('adminuet/', include('mainApp.adminurls')),
    path('statistic/', include(st_urls)),
    path('recommend/', include(rec_urls)),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

K62-RML-statistic_and_recommendation/mainApp/models.py
from django.db import models
import psycopg2
from psycopg2 import extras
from uuid import uuid4
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager

TRAIN_DATA_STORAGE = FileSystemStorage(location=settings.TRAIN_DATA_ROOT)
DUMPED_MODEL_STORAGE = FileSystemStorage(location=settings.DUMPED_MODEL_ROOT)


def get_current_semester():
    today = timezone.now().date()

    semesters = Semesters.objects.filter(beginDay__lte=today).order_by('-beginDay')

    if len(semesters) <= 0:
        semesters = Semesters.objects.filter(endDay__gte=today).order_by('endDay')

    if len(semesters) <= 0:
        current_semester = Semesters.objects.last()
    else:
        current_semester = semesters[0]

    return current_semester


def execute_values(conn, df, table):
    """
    Using psycopg2.extras.execute_values() to insert the dataframe
    """
    # Create a list of tupples from the dataframe values
    tuples = [tuple(x) for x in df.to_numpy()]
    # Comma-separated dataframe columns
    cols = '"' + '","'.join(list(df.columns)) + '"'
    # SQL quert to execute
    query = 'INSERT INTO public."%s"(%s) VALUES %%s' % (table, cols)
    cursor = conn.cursor()
    try:
        extras.execute_values(cursor, query, tuples)
        conn.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        conn.rollback()
        cursor.close()
        return 1
    print("execute_values() done")
    cursor.close()


def model_field_exists(model, field):
    try:
        model._meta.get_field(field)
        return True
    except Exception as e:
        # print(e)
        return False


def create_from_DF(df, model: models.Model, searching_cols: list):
    # for col in df.columns:
    #     if ~model_field_exists(model, col):
    #         print("col: {}".format(col))
    #         df.drop(col, axis=1, inplace=True)
    #         print(df)
    # data for searching the data row
    search = dict.fromkeys(searching_cols)
    # other data use when create
    defaults = dict.fromkeys(list(set(df.columns) - set(searching_cols)))
    # Create a list of tupples from the dataframe values
    object_list = []
    for i, row in df.iterrows():
        for k in search.keys():
            search[k] = row[k]

        for k in defaults.keys():
            defaults[k] = row[k]
        obj, created = model.objects.get_or_create(**search, defaults=defaults)
        object_list.append(obj)
    return object_list


def update_from_DF(df, model: models.Model, searching_cols: list):
    # for col in df.columns:
    #     if ~model_field_exists(model, col):
    #         print("{} is not one of {} field".format(col, model.__name__))
    #         return 1
    # data for searching the data row
    search = dict.fromkeys(searching_cols)
    # other data use when create
    defaults = dict.fromkeys(list(set(df.columns) - set(searching_cols)))

    # Create a list of tupples from the dataframe values
    object_list = []
    for v in df.iterrows():
        for k in search.keys():
            search[k] = v[k]

        for k in defaults.keys():
            defaults[k] = v[k]
        obj, created = model.objects.update_or_create(**search, defaults=defaults)
        object_list.append(obj)
    return object_list


def semester_rank(current_semester_id=None, profile_id: int = None, group_id: int = None, generation_id: int = None,
                  year_id: int = None, semester_id: int = None):
    try:
        if current_semester_id is None:
            current_semester = get_current_semester()
        else:
            current_semester = Semesters.objects.get(pk=current_semester_id)

        if profile_id is not None and profile_id > 0:
            group_id = Profiles.objects.get(pk=profile_id).group_id

        if group_id is not None and group_id > 0:
            generation_id = StudentGroups.objects.get(pk=group_id).generation_id

        if generation_id is not None and generation_id > 0:
            year_id = Generations.objects.get(pk=generation_id).beginningYear_id

        if year_id is not None and year_id > 0:
            semester = Semesters.objects.filter(year_id=year_id).first()
        else:
            semester = Semesters.objects.get(pk=semester_id)

        if current_semester.pk == semester.pk:
            return 0

        sem_begin = semester.beginDay
        cur_sem_begin = current_semester.beginDay

        semester_rank = len(Semesters.objects.filter(endDay__gt=sem_begin, endDay__lt=cur_sem_begin))
        if semester_rank <= 0:
            semester_rank = -len(Semesters.objects.filter(endDay__gt=cur_sem_begin, endDay__lt=sem_begin))

        return semester_rank

    except Exception as e:
        print(e)
        return None


def transcript_path_and_rename(instance: models.Model, filename: str):
    folder_name = 'transcript/'
    filename = filename.replace('/', '_').replace('\\', '_')
    # get filename
    if instance.pk:
        filename = '{}_{}'.format(instance.pk, filename)
    else:
        # set filename as random string
        filename = '{}_{}'.format(uuid4().hex, filename)
    # return the whole path to the file
    return folder_name + filename


class Echo:
    """An object that implements just the write method of the file-like
    interface.
    """
    def write(self, value):
        """Write the value by returning it, instead of storing in a buffer."""
        return value


class Years(models.Model):
    yearID = models.AutoField(primary_key=True)
    yearName = models.CharField(max_length=50)
    openingDay = models.DateField(null=False)
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.yearName

    def save(self, *args, **kwargs):
        other_years = Years.objects.filter(openingDay__year=self.openingDay.year)
        if len(other_years) > 1 or (len(other_years) == 1 and other_years[0].pk != self.pk):
            raise Exception("This year already have opening day")

        super(Years, self).save(*args, **kwargs)


class Semesters(models.Model):
    semesterID = models.AutoField(primary_key=True)
    semesterName = models.CharField(max_length=50)
    year = models.ForeignKey(Years, on_delete=models.CASCADE)
    beginDay = models.DateField(null=False)
    endDay = models.DateField(null=False)

    def __str__(self):
        return self.semesterName


class Units(models.Model):
    unitID = models.AutoField(primary_key=True)
    unitName = models.CharField(max_length=100) #unique=True
    unitDescription = models.CharField(max_length=500, default="", null=True)

    def __str__(self):
        return self.unitName


class Generations(models.Model):
    generationID = models.AutoField(primary_key=True)
    generationName = models.CharField(max_length=10)
    beginningYear = models.ForeignKey(Years, on_delete=models.CASCADE)
    unit = models.ForeignKey(Units, on_delete=models.CASCADE)

    def __str__(self):
        return self.generationName + ' - ' + self.unit.unitName


class StudentGroups(models.Model):
    groupID = models.AutoField(primary_key=True)
    groupName = models.CharField(max_length=25)
    generation = models.ForeignKey(Generations, on_delete=models.CASCADE)

    def __str__(self):
        return self.groupName + ' - ' + self.generation.unit


class Majors(models.Model):
    majorID = models.AutoField(primary_key=True)
    majorName = models.CharField(max_length=100)
    majorDescription = models.CharField(max_length=255, default="", null=True)
    unit = models.ForeignKey(Units, on_delete=models.CASCADE)

    def __str__(self):
        return self.majorName


class Courses(models.Model):
    courseID = models.AutoField(primary_key=True)
    unit = models.ForeignKey(Units, on_delete=models.CASCADE)
    courseCode = models.CharField(max_length=20, unique=True)
    courseName = models.CharField(max_length=100)
    credit = models.IntegerField(default=0)

    def __str__(self):
        return self.courseCode + ' - ' + self.courseName


class Major_Course(models.Model):
    """
    Một mnô học (course) trong mỗi chuyên ngành (major) có thể được đề xuất học trong nhiều kỳ khác nhau (semesterRecommended)
    """
    ID = models.AutoField(primary_key=True)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    major = models.ForeignKey(Majors, on_delete=models.CASCADE)
    semesterRecommended = models.IntegerField(default=0)


class Functions(models.Model):
    """
    Danh sách các chức năng hệ thống để dùng trong việc phân quyền
    """
    functionID = models.AutoField(primary_key=True)
    functionName = models.CharField(max_length=50)

    def __str__(self):
        return self.functionName


class Roles(models.Model):
    """
    Danh sách các vai trò trong hệ thống để phân quyền theo vai trò
    """
    roleID = models.AutoField(primary_key=True)
    roleName = models.CharField(max_length=50)
    roleDescription = models.CharField(max_length=255, default="", null=True)

    def __str__(self):
        return self.roleName


class Role_Function(models.Model):
    """
    Danh sách các chức năng được phân cho các vai trò khác nhau
    """
    ID = models.AutoField(primary_key=True)
    role = models.ForeignKey(Roles, on_delete=models.CASCADE)
    function = models.ForeignKey(Functions, on_delete=models.CASCADE)
    # role = models.IntegerField(blank=False)
    # function = models.IntegerField(blank=False)


class CustomUser(AbstractUser):
    # id | password | last_login | username | date_joined | role_id
    is_superuser = None
    first_name = None
    last_name = None
    email = None
    is_staff = None
    # is_active = None
    groups = None
    user_permissions = None

    role = models.ForeignKey(Roles, null=True, on_delete=models.SET_NULL)
    unit_role = models.IntegerField(default=None, null=True)

    objects = CustomUserManager()

K62-RML-statistic_and_recommendation/mainApp/views.py
from django.shortcuts import render


from django.contrib.auth.decorators import login_required


@login_required(login_url='/login/')
def profile_page(request):
    return render(request, 'student/profile.html')

@login_required(login_url='/login/')
def transcript_page(request):
    return render(request, 'student/transcript.html')

@login_required(login_url='/login/')
def changepassword_page(request):
    return render(request, 'student/changepassword.html')

@login_required(login_url='/login/')
def suggestioncourse_page(request):
    return render(request, 'student/suggestioncourse.html')

@login_required(login_url='/login/')
def scoreforecast_page(request):
    return render(request, 'student/scoreforecast.html')

@login_required(login_url='/login/')
def statistical_page(request):
    return render(request, 'student/statistical.html')

K62-RML-statistic_and_recommendation/mainApp/templates/adminuet/courseform.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">{% if user.is_authenticated %}{{ user.username }}{% endif %}</a></li>
        <li class="breadcrumb-item"><a href="#">Danh mục</a></li>
        <li class="breadcrumb-item active" aria-current="page">Môn học</li>
    </ol>
    <div class=" card">
        <div class="card-body">
            <form class="p-3" method="post" autocomplete="off">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                        {% if messages %}
                            {% for message in messages %}<p>{{ message }}</p>{% endfor %}
                        {% endif %}
                        <div class="form-group row">
                            <div class="col-sm-12">                            
                                {{form.unit|as_crispy_field}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12">
                                {{form.courseCode|as_crispy_field}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12">                            
                                {{form.courseName|as_crispy_field}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12">                            
                                {{form.credit|as_crispy_field}}
                            </div>
                            <div class="col-sm-12">                            
                                <span class="asteriskField"><small>* Bắt buộc.</small></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3"></div>
                </div>
                <div class="form-group  text-center">
                    <button type="submit" id="submit" class="m-4 btn activebutton">Thêm mới</button>
                    <a href="{% url 'course' %}" class="btn activebutton">Quay lại</a>
                </div>
            </form>
        </div> 
    </div>
</div> 
<script type="text/javascript">
    let textBtn = () => {  
        if (document.getElementsByTagName("input")[1].value) document.getElementById("submit").innerText = "Cập nhật";
    }
    textBtn();
    function setSelectBox(){
        let unitRole = {{unitRole}};
        console.log(unitRole);
        if (unitRole != 0) {
            document.getElementById("id_unit").value = unitRole;
            document.getElementById("id_unit").disabled = "disabled";
        }
    }
    setSelectBox();
</script>
{% endblock %}

K62-RML-statistic_and_recommendation/mainApp/templates/adminuet/courseimport.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">{% if user.is_authenticated %}{{ user.username }}{% endif %}</a></li>
        <li class="breadcrumb-item"><a href="#">Danh mục</a></li>
        <li class="breadcrumb-item active" aria-current="page">Môn học</li>
    </ol>
    <div class=" card">
        <div class="card-body">
            <form id="form" class="p-3" method="post" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row text-center">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                        <div class="text-danger">
                            {% if messages %}
                                {% for message in messages %}<p>{{ message|safe }}</p>{% endfor %}
                            {% endif %}
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12">
                                <label for="unit" class=" col-form-label">Trường<span class="asteriskField">*</span></label>
                                <select class="col-sm-12 select2-hidden-accessible custom-select" name="unit" id="unit" required>
                                    {% if units %}
                                        <option value="">Lựa chọn</option>
                                        {% for unit in units %}
                                           <option value="{{ unit.unitID }}">{{ unit.unitName }} </option>
                                        {% endfor %}
                                    {% endif %}
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12">
                                <label for="emdocumentail" class=" col-form-label">Chọn tệp dữ liệu môn học định dạng csv<span class="asteriskField">*</span></label>
                                <input type="file" class="btn pl-3" id="fileinput" name="document" required>
                            </div>
                            <div class="col-sm-12">                            
                                <span class="asteriskField"><small>* Bắt buộc.</small></span>
                            </div>
                        </div>
                    </div>  
                </div>
                <div class="form-group  text-center pt-5">
                    <button type="submit" class="btn activebutton" onclick="validateFile()">Đăng tải tệp này</button>
                    <a href="{% url 'course' %}" class="btn activebutton">Quay lại</a>
                </div>
            </form>
        </div> 
    </div>        
</div> 
{% endblock %}

K62-RML-statistic_and_recommendation/mainApp/templates/adminuet/generation.html
{% extends "./base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/unit.css' %}">
<div class="container">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">{% if user.is_authenticated %}{{ user.username }}{% endif %}</a></li>
        <li class="breadcrumb-item"><a href="#">Danh mục</a></li>
        <li class="breadcrumb-item active" aria-current="page">Khóa</li>
    </ol>
    {% include 'student/successmessage.html' %}
    <div class=" card">
        <div class="card-header">
            <h5>Khóa</h5>
        </div>
        <div class="card-body">
            <div class="card-title row">
                <div class="col-sm-7">
                    <a href="{% url 'generation-import-page' %}" class="btn activebutton">Nhập file</a>
                    <a href="{% url 'generation-export-page' %}" class="btn activebutton">Xuất file</a>
                    <a href="{% url 'generation-form' %}" class="btn activebutton">Thêm mới</a>
                    <select id="numberofrow" class="custom-select col-sm-2" onchange="redictUrlClickOption()">
                        <option value="10">10</option>
                        <option value="50">50</option>
                        <option value="100" >100</option>
                        <option value="1000">1000</option>
                        <option value="3000">3000</option>
                    </select>
                </div>
                <div class=" form-inline col-sm-5">
                    <input class="form-control col-sm-12 inline" id="myInput" type="text" onkeyup="searchThreeField()" placeholder="Tìm kiếm...">
                </div>
            </div>
            <table class="table" id="myTable">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">STT</th>
                        <th scope="col">Tên khóa</th>
                        <th scope="col">Năm bắt đầu học</th>
                        <th scope="col">Trường</th>
                        <th scope="col">Thao tác</th>
                    </tr>
                </thead>
                <tbody id="table-body">
                </tbody>
            </table>
            <div class="text-center">
            <nav aria-label="Page navigation ">
                <ul id="pagination" class="pagination justify-content-center"></ul>
            </nav>
            </div>
        </div> 
    </div>
</div> 
<script type="text/javascript" src="{% static 'js/table.js' %}"></script>
<script type="text/javascript">
    let pathAdmin = '/adminuet';
    let url_api = '';
    let offset = ({{ page }} - 1) * getNumberOfRowInSelections(); //offet để truyền vào api để truy vấn từ ví trí offset
    let limit = {{limit}}; //limt lấy ban đầu từ url page1/limit10/ là giá trị mặc định
    let pathForPage = '/generation/page';
    let pathApiGetList = '/generation-getlist/';
    let currentPage = {{page}};
    
    main(offset, limit);

    /*
    Hàm renderTable() nhận đầu vào là dữ liệu json của fetchJson đã get từ API
    render ra các dòng và thao tác ở trong bảng dữ liệu.
    */
    function renderTable(mydata){
        let url_update = pathAdmin + '/generation-form/';
        let url_delete = pathAdmin + '/generation-delete/';
        let units = mydata.data;
        let rowHTML = [];
        for (let [index, data] of units.entries()){
            let tempIndex = index + 1 + limit * ({{ page }} - 1);
            let row = '<tr>'
                    + '<td>' + tempIndex + '</td>'
                    + '<td>' + encodeHTML(data.generationName) + '</td>'
                    + '<td>' + encodeHTML(data.beginningYear) + '</td>'
                    + '<td>' + encodeHTML(data.unit) + '</td>'
                    + "<td><a href=\"" + url_update  + data.generationID + "\"> Sửa </a> | "
                    + "<a onclick=\"checkArgeeDelete()\" href=\"" + url_delete  + data.generationID + "\"> Xóa</a></td>"
                    + '</tr>';
            rowHTML.push(row);
        }
        document.getElementById("table-body").innerHTML += rowHTML.join("");
    }
    checkArgeeDelete = function(){
        let msg = confirm("Xóa dữ liệu này sẽ mất hết các dữ liệu khác liên quan.\nBạn chắc chắn muốn xóa?");
        if (!msg) {
            event.preventDefault();
        }
    }
</script>
{% comment %} <script type="text/javascript" src="{% static 'js/sort.js' %}"></script> {% endcomment %}
<script type="text/javascript" src="{% static 'js/searchtwofield.js' %}"></script>
{% endblock %}

K62-RML-statistic_and_recommendation/mainApp/templates/adminuet/semesterimport.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">{% if user.is_authenticated %}{{ user.username }}{% endif %}</a></li>
        <li class="breadcrumb-item"><a href="#">Danh mục</a></li>
        <li class="breadcrumb-item active" aria-current="page">Học kỳ</li>
    </ol>
    <div class=" card">
        <div class="card-body">
            <form id="form" class="p-3" method="post" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md-3">
                        <label for="email" class=" col-form-label">Chọn tệp dữ liệu định dạng csv:</label>
                    </div>
                    <div class="col-md-8">
                        <input type="file" class="btn pl-3" id="fileinput" name="document">
                        <div class="text-danger pt-3">
                            {% if messages %}
                                {% for message in messages %}
                                    <strong>{{ message|safe }}</strong>
                                {% endfor %}
                            {% else %}
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="form-group  text-center pt-5">
                    <button type="submit" class="btn activebutton" onclick="validateFile()">Đăng tải tệp này</button>
                    <a href="{% url 'semester' %}" class="btn activebutton">Quay lại</a>
                </div>
            </form>
        </div> 
    </div>        
</div> 
<script type="text/javascript">
</script>
{% endblock %}

K62-RML-statistic_and_recommendation/mainApp/templates/adminuet/trainingframeworkform.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<link href="{% static 'css/select2.min.css' %}" rel="stylesheet" />
<style>
.select2-container{width:100%!important}
b{margin-top: 2px !important}
.select2-selection{
    border: 1px solid #ced4da!important;
    height: calc(1.5em + .75rem + 2px)!important;
    padding: .2rem .25rem !important;
}
</style>
<div class="container">
    <ol class="breadcrumb"> 
        <li class="breadcrumb-item"><a href="#">{% if user.is_authenticated %}{{ user.username }}{% endif %}</a></li>
        <li class="breadcrumb-item"><a href="#">Danh mục</a></li>
        <li class="breadcrumb-item active" aria-current="page">Khung đào tạo</li>
    </ol>
    <div class=" card">
        <div class="card-body">
            <form class="p-3" method="post" autocomplete="off">
                {% csrf_token %}
                <div class="row text-center">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                        <div class="text-danger">
                            {% if messages %}
                                {% for message in messages %}<p>{{ message }}</p>{% endfor %}
                            {% endif %}
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12">
                                {{form.course|as_crispy_field}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12">                            
                                {{form.major|as_crispy_field}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12">
                                {{form.semesterRecommended|as_crispy_field}}
                            </div>
                            <div class="col-sm-12">                            
                                <span class="asteriskField"><small>* Bắt buộc.</small></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3"></div>
                </div>
                <div class="form-group  text-center">
                    <button type="submit" id="submit" class="m-4 btn activebutton">Thêm mới</button>
                    <a href="{% url 'trainingframework' %}" class="btn activebutton">Quay lại</a>
                </div>
            </form>
        </div> 
    </div>        
</div> 
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/select2.min.js' %}"></script>
<script>
    let textBtn = () => {  
        if (document.getElementsByTagName("input")[1].value != 0) document.getElementById("submit").innerText = "Cập nhật";
    }
    textBtn();
    $(document).ready(function() {
        $('#id_course').select2();
        $('#id_major').select2();
    });
    function getMapCousers(){
        let map = new Map();
        {% for course in cousers %}
            map.set({{course.courseID}}, '{{course}}');
        {% endfor %}
        return map;
    }
    function getMapMajor(){
        let map = new Map();
        {% for major in majors %}
            map.set({{major.majorID}}, '{{major}}');
        {% endfor %}
        return map;
    }
    console.log(getMapMajor());
    function getArrayKeyInMap(map) {
        let arr = [];
        for (let [index, data] of map.entries()) {
            arr.push(index);
        }
        return arr;
    }

    function setSelectBoxCourse(){
        let map = getMapCousers();
        let arr = getArrayKeyInMap(map);
        let courseSelect = document.getElementById("id_course");
        let arrResult = [];
        for (let i = 1; i < courseSelect.length; i++) {
            if (arr.indexOf(parseInt(courseSelect.options[i].value)) == -1) {
                arrResult.push(courseSelect.options[i].value);
            }
        }
        for (let element in arrResult) {
            for (let i = 0; i < courseSelect.length; i++){
                if (courseSelect.options[i].value == arrResult[element]){
                    courseSelect.remove(i);
                }
            }
        }
    }
    function setSelectBoxMajor(){
        let map = getMapMajor();
        let arr = getArrayKeyInMap(map);
        let courseSelect = document.getElementById("id_major");
        let arrResult = [];
        for (let i = 1; i < courseSelect.length; i++) {
            if (arr.indexOf(parseInt(courseSelect.options[i].value)) == -1) {
                arrResult.push(courseSelect.options[i].value);
            }
        }
        for (let element in arrResult) {
            for (let i = 0; i < courseSelect.length; i++){
                if (courseSelect.options[i].value == arrResult[element]){
                    courseSelect.remove(i);
                }
            }
        }
    }
    
    function main(){
        let unitRole = {{unitRole}};
        if (unitRole > 0) {
            setSelectBoxCourse();
            setSelectBoxMajor();
        }
    }
    main();
</script>
{% endblock %}